language: node_js
node_js:
  - "8"

cache:
  directories:
  - functions/node_modules

before_install:
  - npm install -g firebase-tools
  - cd functions
  - npm install
  - cd ..

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
